### ISSUE TITLE
News ページの作成をお願いいたします

### ISSUE THREAD

**Issue by sasuke0339** [cm-devcamp/devcamp_app2_wada#1]
# 概要

トップページの、ニュース一覧から特定のニュースをクリックすることで、当該のニュースページにアクセスできるようにしてください。

## 担当者

cm-hiyo さんに主にご対応いただけるかと思いますが、明日中に終わらなかった場合は cm-sagojo さんにもご協力お願いできれば幸いです。

## 期待する動作

1. 特定のニュースをクリック
2. 当該ページにアクセス

### 注意点

以下の要件で作成をお願いいたします。

- ヘッダーは画面遷移後も同じものを流用
- app/components/ 配下にニュースページ用のコンポーネントを作成
- app/ 配下に新しくニュースページ用のファイルを作成し、作成したコンポーネントを呼び出す（ app.tsx の Home() の書き方に合わせる形でお願いします）
- ニュースの内容は devcamp_news.json から取得
- devcamp_news.json の id をそのまま URL とする
- ひとまず作成していただき、お客様に UI のレビューをしていただく形

以上よろしくお願いいたします。

**Comment by cm-hiyo** [comment]
了解です。作業始めます。
シフトが木曜日と金曜日なので終わらなかったらsagojoさんへの引き継ぎをお願いします。
今日進んだ分はここで報告します。

**Comment by sasuke0339** [comment]
@cm-hiyo 
かしこまりました、ありがとうございます。
よろしくお願いいたします。
