### ISSUE TITLE
商品一覧ページと各商品ページの作成依頼

### ISSUE THREAD

**Issue by sasuke0339** [cm-devcamp/devcamp_app2_wada#2]
# 概要

商品一覧ページと各商品専用ページを作成

## 担当者

主に cm-moro さんにご対応いただければと思います。News ページの作成を cm-hiyo さんと cm-sagojo さんにしていただく予定ですので、push され次第そちらを参考に作業していただければ幸です。  
また、cm-sagojo さんにはフォローしていただきたく思います。不明点等あれば、コメントいただければ私からお答えもできますので、お気軽にご相談ください。

## 期待する動作（商品一覧ページ）

- Products ボタンを押下すると商品一覧ページにアクセスできる
- 写真と商品名、価格が表示されるような一般的な EC サイト
  - ヘッダーはトップページと同様のものを流用
  - 楽天市場のような形で表示
- 商品をクリックすると各商品ページにアクセスする

## 期待する動作（各商品ページ）

- 商品一覧ページから各商品ページにアクセスできる
- 一覧ページよりも詳細に商品について知ることができる必要があるので、JSON ファイルの description の内容も表示する
  - 各商品の詳細がわかるようにしたい
- 商品画像が強調されるような UI にする

## 注意点

以下の要件で作成をお願いいたします。

- ヘッダーは画面遷移後も同じものを流用
- app/ 配下に新しく各 tsx ファイルを作成
- 商品詳細は devcamp_products.json から取得
- 各商品ページでは devcamp_products.json の id をそのまま URL とする

以上よろしくお願いいたします。

**Comment by cm-sagojo** [comment]
分かりました。一点確認なのですが、以下の作業は具体的にどのようなことをするのでしょうか。

> app/components/ 配下にそれぞれのコンポーネントを作成

**Comment by sasuke0339** [comment]
@cm-sagojo 
ありがとうございます。
JSON ファイルから情報を取って来て、ページに表示されるようにしたいので、以下にある同ディレクトリにある news.tsx の当該箇所のように各値を設定して JSON から取得していただけるのではないかと想定しております。

```
interface News {
  id: number;
  title: string;
  description: string;
  url: string;
  datems: number;
}

export default function NewsList() {
  const news: News[] = newsData;

  return (
    <div className="flex-col w-full max-w-5xl items-center justify-between p-6 bg-slate-50">
      {news.map((topic) =>
        <div className="flex" key={topic.id}>
            <div className="pt-1 pb-1">
              {new Date(topic.datems).toLocaleDateString("ja-JP")}
            </div>
            <div className="grow pt-1 pb-1 pl-4">
              <Link href={`/news/${topic.id}`}>{topic.title}</Link>
            </div>
        </div>
      )}
    </div>
  )
}
```

**Comment by sasuke0339** [comment]
@cm-sagojo @cm-moro 
お疲れ様です。方針の変更をしますので、共有いたします。  
ご質問いただいておりました component を作成して呼び出す形にする件ですが、現状の規模を考えると component を作成して切り出すメリットが少ないため、各ページを app/ 配下に作成する方針で問題ありません。

もちろん component を作成していただいても問題ありませんので、その辺りはお任せする形になるかと存じます。  
お手数ではございますがよろしくお願いいたします。

**Comment by cm-moro** [comment]
@sasuke0339 
P-Rを提出しました。
https://github.com/cm-devcamp/devcamp_app2_wada/pull/4
