### ISSUE TITLE
商品一覧ページについて追加要件

### ISSUE THREAD

**Issue by sasuke0339** [cm-devcamp/devcamp_app2_wada#5]
# 概要

お客様からの要件の伝達漏れです。大変失礼いたしました。
一覧ページに表示する商品を「最新10件」にしていただきたいです。

## 期待する動作

- 表示される商品が最新10件になる
- 最新商品を目立たせたいため、更新日順で上から降順
  - トップに2024/7/23、下に2024/7/22

**Comment by cm-moro** [comment]
@sasuke0339 
これからその実装をするのは手戻りが大きく対応が難しいです。
jsonの並べ方を変更するなどして先方側でご対応をお願いできないでしょうか。

**Comment by sasuke0339** [comment]
@cm-moro 
お疲れ様です。cm-moro さんはどのような修正を想定されておりますでしょうか。
私の想定では、Page() の冒頭で配列 productList を宣言した部分で、datems を利用した降順にソートし、slice で最新10件に絞り込めるのではないかと考えておりますが、いかがでしょうか。
```
  const productList: Products[] = products;
```
